import Head from 'next/head'
import Link from 'next/link'

export function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>{children}</main>
      <ul
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          width: '100%',
          opacity: 0.5,
          background: '#fff',
        }}
      >
        <Link href='/'>Home</Link>
        <br />
        <Link href='/scene-1'>scene-1 (moving-gradient)</Link>
        <br />
        <Link href='/scene-fading-image'>scene-fading-image</Link>
      </ul>
    </>
  )
}
